package com.universalrandomizer.features;

import com.universalrandomizer.config.RandomizerMode;
import com.universalrandomizer.core.RandomizerManager;
import com.universalrandomizer.util.RandomizerLogger;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;

/**
 * Randomizes furnace smelting result outputs across Furnaces, Blast Furnaces,
 * and Smokers.
 */
public final class SmeltingRandomizer {

    private SmeltingRandomizer() {}

    /**
     * Randomizes an output {@link ItemStack} generated by smelting.
     * Preserves stack count and tags.
     */
    public static ItemStack randomizeSmeltingResult(ItemStack vanillaOutput) {
        if (vanillaOutput == null || vanillaOutput.isEmpty()) return vanillaOutput;

        RandomizerManager mgr = RandomizerManager.getInstance();
        if (!mgr.isInitialized() || !mgr.isEnabled(RandomizerMode.SMELTING)) return vanillaOutput;

        ResourceLocation itemKey = BuiltInRegistries.ITEM.getKey(vanillaOutput.getItem());
        if (itemKey == null) return vanillaOutput;

        ResourceLocation targetKey = mgr.getSmeltingOutput(itemKey);
        if (targetKey == null || targetKey.equals(itemKey)) {
            targetKey = mgr.getTable().lookup(
                mgr.getTable().getMiningDrops(), itemKey, new java.util.Random());
        }

        ResourceLocation finalKey = targetKey;
        return BuiltInRegistries.ITEM.getOptional(finalKey)
            .map(item -> {
                ItemStack result = new ItemStack(item, vanillaOutput.getCount());
                if (vanillaOutput.hasTag()) {
                    result.setTag(vanillaOutput.getTag().copy());
                }
                RandomizerLogger.debug("Smelting Result: {} -> {} (x{})", itemKey, finalKey, result.getCount());
                return result;
            })
            .orElse(vanillaOutput);
    }
}
